### ISSUE TITLE
Day or Night GR Skyline image based on time of day

### ISSUE THREAD

**Issue by ajhekman** [friendlycode/viget-theme#1]
Thoughts on making the homepage GR skyline image cycle by time of day?

**Comment by pichot** [comment]
That would be awesome. How would you implement it? Use the server time or browser's time?

**Comment by ajhekman** [comment]
I was thinking server-side, but I suppose either work equally well.

**Comment by chaselee** [comment]
Viget does its rendering server-side, right? If so, then I don't think it
really matters.
For time zone, I think it'd be cool to show pictures that correspond to the
actual time in Grand Rapids (EST).
I also had this crazy idea that friendly code could make opening up all the
gr camera feeds one of its projects, then all the skyline cams could be
piped right into the homepage of viget. Users could even choose different
locations to show up on their homepage. Absolutely crazy, I know, but it
sure does sound cool.

On Wed, Jan 9, 2013 at 10:21 AM, Andrew Hekman notifications@github.comwrote:

> I was thinking server-side, but I suppose either work equally well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/friendlycode/viget-theme/issues/1#issuecomment-12048651.

## 

Chase Lee http://chase-lee.com/
umchaselee@gmail.com
616.272.8766
Twitter https://twitter.com/_chaselee,
Facebookhttps://www.facebook.com/umchaselee,
Linkedin https://www.linkedin.com/in/umchaselee/
